# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupBuyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='maxUsers',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='lot',
            name='minUsers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lot',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
