# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupBuyApp', '0003_auto_20171207_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
