# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GroupBuyApp', '0004_remove_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
